### ISSUE TITLE
habr dark

### ISSUE THREAD

**Issue by Owyn** [valsaven/userstyles#28]
![image](https://user-images.githubusercontent.com/1309656/131833797-1fcccd69-4aaa-4761-bf04-b73e17cf7439.png)

https://habr.com/ru/news/t/575732/

**Comment by valsaven** [comment]
Try to update. The latest version of the styles should be fine.

**Comment by Owyn** [comment]
https://greasyfork.org/en/scripts/407862-habrahabr-darkness
2.0.1 version

after update - all OK

**Comment by Owyn** [comment]
again same problem

https://habr.com/ru/post/467237/
![image](https://user-images.githubusercontent.com/1309656/132858790-8581fb30-c21f-4cd9-a4e3-3b5b9a888198.png)

**Comment by valsaven** [comment]
It should work fine with 2.0.6 version. Can you check it?

**Comment by Owyn** [comment]
Auto-updating seems to be slow

now it works with 2.0.6,but scrollbar is still white:
![image](https://user-images.githubusercontent.com/1309656/132859411-b4630ebc-ae17-4d35-9ae2-c44208d1d179.png)

**Comment by Owyn** [comment]
Now it doesn't work again, I have no idea why, 2.0.6
![image](https://user-images.githubusercontent.com/1309656/132862006-09faa881-e36a-4fa4-b1b2-10dba94dac66.png)

**Comment by Owyn** [comment]
![image](https://user-images.githubusercontent.com/1309656/132862408-999ba31b-bbff-4563-89b7-fc27895fff39.png)

**Comment by valsaven** [comment]
Oh, thank you. I think I understand now. I'm going to fix it.

**Comment by valsaven** [comment]
Try updating to version 2.0.7 =) This should fix the problem

**Comment by Owyn** [comment]
Seems to be working now, thx.

**Comment by Owyn** [comment]
Same problem again w 2.0.9: 
![изображение](https://user-images.githubusercontent.com/1309656/136692059-60c97f6b-0873-442f-99a0-5d1c1882d12c.png)

**Comment by mammuthus** [comment]
Same issue with the latest (October 8, 2021) "Habrahabr Darkness" style.
![image](https://user-images.githubusercontent.com/1700286/138933372-dcbee684-6bae-416d-9a72-27aac7a5b0a5.png)
